### ISSUE TITLE
Set up travis building of this repo

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-fx2-firmware#3]
We should be building the firmware on every commit.

The travis code for the HDMI2USB-litex-firmware is here ->
https://github.com/timvideos/HDMI2USB-litex-firmware/blob/master/.travis.yml

**Comment by mithro** [comment]
It will need to do things like
 * Install sdcc 
   - Do we want to check multiple sdcc versions?
   - Definitely want to test with the latest sdcc versions
 * Compile firmware
   -  (maybe) Upload the firmware.hex files somewhere (prebuilt repo?)
   - Should check it compiles for all dev boards
 * Generates docs
   - Doxygen

**Comment by mithro** [comment]
Good example to follow mithro/fx2lib 's travis -> https://github.com/mithro/fx2lib/blob/master/.travis.yml

**Comment by mithro** [comment]
See https://github.com/timvideos/HDMI2USB-litex-firmware/issues/60 also

**Comment by paddatrapper** [comment]
This is done now, correct?

**Comment by mithro** [comment]
Yeap!
