### ISSUE TITLE
Create LED blinking test firmware

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-fx2-firmware#5]
We need an FX2 firmware which flashes the LEDs connected to the FX2.

**Comment by paddatrapper** [comment]
There is an example in the fx2lib examples directory that does this, however it is currently failing to build:

    make -C lights lights
    make[1]: Entering directory '/home/kyle/projects/opsis/HDMI2USB-fx2-firmware/third_party/fx2lib/examples/lights'
    sdcc -mmcs51  --code-size 0x3c00 --xram-size 0x0200 --xram-loc 0x3c00       lights.c   -o lights
    lights.c:19:21: fatal error: fx2regs.h: No such file or directory
    compilation terminated.
    lights.c:1: warning 190: ISO C forbids an empty source file
    <builtin>: recipe for target 'lights' failed
    make[1]: *** [lights] Error 1
    make[1]: Leaving directory '/home/kyle/projects/opsis/HDMI2USB-fx2-firmware/third_party/fx2lib/examples/lights'
    Makefile:9: recipe for target 'lights' failed
    make: *** [lights] Error 2

**Comment by mithro** [comment]
@paddatrapper - I think this is done now.
